### ISSUE TITLE
No variable_scope in tf 2.0. model.py needs fix.

### ISSUE THREAD

**Issue by vishal-keshav** [vishal-keshav/fast_prototype#4]
In model file for example in `architecture/version1/model.py` reports an error as shown below:

```
Traceback (most recent call last):
  File "model.py", line 160, in <module>
    arch_dict = create_model(img)
  File "model.py", line 152, in create_model
    net.build_model(img)
  File "model.py", line 51, in build_model
    with tf.variable_scope("", reuse = tf.AUTO_REUSE):
AttributeError: module 'tensorflow' has no attribute 'variable_scope'
```

There is no variable_scope in tf 2.0.
I am not sure what replaces this functionality from the previous tf version.

The error can be reproduced by `python3 model.py` after heading to the architecture/version1 directory.

**Comment by JonGeorge** [comment]
Got it. I will look into this issue!

**Comment by vishal-keshav** [comment]
Thanks Jon

**Comment by JonGeorge** [comment]
@vishal-keshav I just submitted a PR to resolve this issue. As a quick fix, I updated the functions to use the tf.compat.v1 api. A more long term solution may potentially involve re-architecting your model.

**Comment by vishal-keshav** [comment]
Thanks Jon. We will make a detailed plan to re-architect the model that removes this API. Closing this as this has been resolved.
